[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6 --preverify --always-print-stacktrace --no-location --catch-hardfault"

[env]
DEFMT_LOG = "info"
SSID = ""
PASSWORD = ""
BROKER_ADDRESS = ""
CLIENT_ID = ""
MQTT_USERNAME = ""
MQTT_PASSWORD = ""

[build]
rustflags = ["-C", "force-frame-pointers"]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
